name: ci

on:
  push:
    branches:
      - 'main'

env:
  REGISTRY: ghcr.io

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Docker meta
        id: meta_worker
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/dialohq/tink-worker
          tags: |
            type=sha,prefix=sha-

      -
        name: Docker meta
        id: meta_flatcar_install
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/dialohq/flatcar-install
          tags: |
            type=sha,prefix=sha-

      - 
        name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - 
        name: Checkout
        uses: actions/checkout@v3
      
      -
        name: Build and push (flatcar)
        uses: docker/build-push-action@v2
        with:
          context: flatcar-install
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_flatcar_install.outputs.tags }}
          labels: ${{ steps.meta_flatcar_install.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/dialohq/flatcar-install:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/dialohq/flatcar-install:buildcache,mode=max

      -
        name: Build and push (tink-worker)
        uses: docker/build-push-action@v2
        with:
          context: tink-worker
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta_worker.outputs.tags }}
          labels: ${{ steps.meta_worker.outputs.labels }}
          cache-from: type=registry,ref=${{ env.REGISTRY }}/dialohq/tink-worker:buildcache
          cache-to: type=registry,ref=${{ env.REGISTRY }}/dialohq/tink-worker:buildcache,mode=max

